spring:
  data:
    mongodb:
      uri: mongodb://192.168.2.128:30017/esms

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false

  datasource:
    url: jdbc:postgresql://192.168.2.128:30432/master
    username: dba
    password: pg_pass
    driver-class-name: org.postgresql.Driver

dubbo:
  application:
    name: esms-consumer
  zookeeper:
    address: zookeeper://192.168.2.128:32181
    file: N/A
  annotation:
    package: com.zss.esms.web
  consumer:
    version: 1.0.1
    timeout: 300000
    check: false