spring:
  data:
    mongodb:
      uri: mongodb://192.168.2.200:30017/esms

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false

  datasource:
    url: jdbc:postgresql://192.168.2.200:30432/master
    username: dba
    password: pg_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 60000

dubbo:
  application:
    name: esms-consumer
  zookeeper:
    address: zookeeper://192.168.2.200:32181
    file: N/A
  annotation:
    package: com.zss.esms.web
  consumer:
    version: 1.0.1
    timeout: 300000
    check: false